name: CD
on:
  push:
    tags:
      - v*.*.*
jobs:
  goreleaser:
    name: GoReleaser Publish
    permissions:
      contents: write
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - uses: AtomiCloud/actions.cache-bun@v1
      - name: Compile, package, and publish all channels
        run: nix develop .#releaser -c ./scripts/release/publish.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          SCOOP_BREW_TOKEN: ${{ secrets.SCOOP_BREW_TOKEN }}
  docker:
    name: Docker Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      image_name: diene-bun-cli
      dockerfile: ./infra/Dockerfile
      version: ${{ github.ref_name }}
