name: ⚡ Reusable Compile
on:
  workflow_call:
jobs:
  compile:
    name: Compile Binaries
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - uses: AtomiCloud/actions.cache-bun@v1
      - name: Cross-compile standalone binaries
        run: nix develop .#ci -c pls compile
      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          name: cli-binaries
          path: dist/bin/
          if-no-files-found: error
